services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: atividade_asa_proxy
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - dns
      - web1
      - web2

  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: atividade_asa_dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - app_network

  web1:
    build:
      context: ./web1
      dockerfile: Dockerfile
    container_name: atividade_asa_web1
    networks:
      - app_network

  web2:
    build:
      context: ./web2
      dockerfile: Dockerfile
    container_name: atividade_asa_web2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

